spring:
  graphql:
    cors:
      allowed-origins: "*"
    graphiql:
      enabled: true
    websocket:
      path: "/graphql-ws"
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 50

jwt:
  sharedSecret: change-me
  hours-valid: 168 # One week

password:
  salt: $2a$09$/hJXJVlOfryvAa2s2ifKw.yei76MTsHlWCF0wqHkbUZ34rOZ0jtwy

samples:
  jid-codes: 5000
  locations: 2
  years-per-location: 10
  min-participants-per-location: 20
  max-participants-per-location: 90
  users: 10
  found-jid-codes-for-participant-max: 200
  found-jid-codes-for-participant-mean: 100
  found-jid-codes-for-participant-std-dev: 50
