# CircleCI configuration file

version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.8
    resource_class: arm.medium
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: ./mvnw -B -Pnative spring-boot:build-image
