# CircleCI configuration file

version: 2.1

executors:
  amd64:
    docker:
      - image: cimg/openjdk:17.0.8
    resource_class: large
  aarch64:
    docker:
      - image: cimg/openjdk:17.0.8
    resource_class: arm.large


jobs:
  build:
    parameters:
      platform:
        type: executor
    executor: << parameters.platform >>
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: uname -m
      - run: ./mvnw -B -Pnative -Dspring-boot.build-image.imageName=ghcr.io/jotajoti/jid-server-spring:$CIRCLE_SHA1-$(uname -m) spring-boot:build-image
      - run:
          name: Save image as tar
          command: |
            mkdir -p images
            docker image save -o "images/jid-server-spring_$CIRCLE_SHA1-$(uname -m)" "ghcr.io/jotajoti/jid-server-spring:$CIRCLE_SHA1-$(uname -m)"
      - persist_to_workspace:
          root: .
          paths:
            - images
  push-images:
    executor: amd64
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load images
          command: |
            docker image load < "images/jid-server-spring_$CIRCLE_SHA1-amd64"
            docker image load < "images/jid-server-spring_$CIRCLE_SHA1-aarch64"
      - run:
          name: Authenticate ghcr
          command: echo $GITHUB_TOKEN | docker login ghcr.io -u jotajoti --password-stdin
      - run:
          name: Build and push multi-arch image
          command: docker buildx imagetools create --tag=ghcr.io/jotajoti/jid-server-spring:$CIRCLE_SHA1 ghcr.io/jotajoti/jid-server-spring:$CIRCLE_SHA1-aarch64 ghcr.io/jotajoti/jid-server-spring:$CIRCLE_SHA1-amd64

workflows:
  build-and-push:
    jobs:
      - build:
          matrix:
            parameters:
              platform: [ amd64, aarch64 ]
      - push-images:
          requires:
            - build
