name: "Build and push Docker images"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        builder:
          - ashaun/builder-arm:base
          - paketobuildpacks/builder:base

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica

      - name: Build native image
        run: mvn -B -Dspring-boot.build-image.builder=${{ matrix.builder }} -Pnative spring-boot:build-image --file pom.xml
