name: "Create tag and bump version"

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version in the format X.Y.Z, eg. 1.2.0 (leave blank for auto-increment)'
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Configure Git user
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Tag and bump
        run: ./mvnw -B -DreleaseVersion=${{ inputs.releaseVersion }} compile test-compile release:prepare --file pom.xml
